### ISSUE TITLE
Publishing

### ISSUE THREAD

**Issue by gwennlbh** [ewen-lbh/zed-wakatime#3]
We're getting close to a first serious release!

Things to do:

- [ ] Make sure wakatime-lsp downloads wakatime-cli (see https://github.com/mrnossiom/wakatime-lsp/pull/5)
- [ ] Publish to zed's registry (see https://github.com/zed-industries/extensions/blob/main/AUTHORING_EXTENSIONS.md#publishing-your-extension)
- [ ] Notify Wakatime about the editor plugin!!
- [ ] Notify watchers on https://github.com/zed-industries/extensions/issues/497

**Comment by rodneyosodo** [comment]
The second step can be automated using GitHub action whenever there is a version update we update the [extensions repo](https://github.com/zed-industries/extensions) in zed-industries since it depends on submodules

**Comment by gwennlbh** [comment]
Yes! I have experience setting that up for [ortfo](https://ortfo.org) (the documentation sites pulls content from the source code of the actual software's repo, namely generated JSON schemas of Go structs)

It basically consists of two parts:

1. Dispatch a workflow event when a push with tag happens here (e.g. https://github.com/ortfo/db/blob/main/.github/workflows/update-docs.yaml)
2. Listen for workflow dispatches, and update the submodule in zed-industries/extensions (e.g. https://github.com/ortfo/website/blob/main/.github/workflows/update-submodules.yml)

But I doubt this repo will often have releases, so it may not be worth setting all of this up :thinking:

**Comment by rodneyosodo** [comment]
There is an easier process https://github.com/zed-industries/extensions/blob/main/AUTHORING_EXTENSIONS.md#updating-an-extension

**Comment by gwennlbh** [comment]
See #10
