### ISSUE TITLE
time is not getting tracked on my dashboard 

### ISSUE THREAD

**Issue by volfiros** [ewen-lbh/zed-wakatime#4]
I have followed the instructions on the readme and installed the dev extension but my coding time is not getting tracked on my wakatime dashboard.

Installed `wakatime-cli` using 
```
brew install wakatime-cli
```

OS : Linux (Fedora 40)
Version: 0.143.7 (latest)

![Screenshot from 2024-07-15 01-04-17](https://github.com/user-attachments/assets/21fb793a-00e6-474c-b0a7-5a0ced53f998)

**Comment by volfiros** [comment]
@ewen-lbh please look into this
Thanks!

**Comment by gwennlbh** [comment]
I'll need a few things:

- Any relevant logs from `~/.local/share/zed/logs/Zed.log`
- Any logs that are produced by the language server -- reload your workspace, open any file in a supported language, and open the "language server logs", you can click on the language server name to switch to wakatime's logs 
- If there's still nothing obvious, you can try adding `RUST_LOG`, setting it to `debug` in the `env` then rebuilding the extension (see the language server options function at the end of the source file)

**Comment by gwennlbh** [comment]
By "supported languages" i mean one of these:

https://github.com/ewen-lbh/zed-wakatime/blob/main/extension.toml#L12

**Comment by volfiros** [comment]
@ewen-lbh Idk what happened but time tracking seems to be working now after I reinstalled the extension
Btw the editor has become slow is this because of this extension?
