### ISSUE TITLE
Extension is not installed

### ISSUE THREAD

**Issue by berkus** [ewen-lbh/zed-wakatime#6]
I'm following the steps outlined in the readme, Extensions > Install Dev Extension, pick a folder, and nothing else happens apart from these two log lines:

```
2024-08-04T14:48:29.422224Z [INFO] compiling Rust extension /Users/berkus/Hobby/Rust/zed-wakatime
2024-08-04T14:48:29.573193Z [INFO] compiling rust extension /Users/berkus/Hobby/Rust/zed-wakatime
```

----

**Add:**

That's on Zed `0.146.5`
rustc --version `rustc 1.80.0 (051478957 2024-07-21)` installed via rustup

rust toolchains and targets installed:
❯ rustup toolchain list
stable-aarch64-apple-darwin (default)
nightly-aarch64-apple-darwin

❯ rustup +stable target list --installed
aarch64-apple-darwin
aarch64-apple-ios
aarch64-unknown-linux-gnu
aarch64-unknown-none-softfloat
thumbv6m-none-eabi
thumbv7em-none-eabihf
wasm32-wasi
x86_64-apple-ios

❯ rustup +nightly target list --installed
aarch64-apple-darwin
aarch64-unknown-none-softfloat
thumbv6m-none-eabi
thumbv7em-none-eabihf
wasm32-unknown-unknown

**Comment by lvillalobos-cr** [comment]
Running into the same issue. Tried to check the website to see if it was sending anything and it looks like it's not working

**Comment by gwennlbh** [comment]
Welp its kinda hard to figure out what's happening with such little logs, but unfortunately the Zed situation on extension debugging is kinda rough (i mean it is what it is, it's a very recent thing)

I'll try to repro this and see if I can work sth out, but I don't really have much time until a bit after summer vacation unfortunately 

 publishing the extension (#3) may make the problem go away as this installation method is kinda hacky but we'll have to see...

Of course if someone figures something out i'll gladly take a PR ;)

**Comment by Gasiyu** [comment]
Make sure you have rust installed, mine is working after swapping my distro prepackaged rust with rust installed from rutsup

**Comment by berkus** [comment]
> Make sure you have rust installed, mine is working after swapping my distro prepackaged rust with rust installed from rutsup

Yeah, I have rust installed from rustup all the time, I wonder what else may I be missing? I have both stable and nightly, a bunch of toolchains installed too, so whatever it misses it does not say.

**Comment by berkus** [comment]
I have added my relevant configuration to the OP.

**Comment by gwennlbh** [comment]
Your rust setup looks totally fine, I did not build this on nightly, I'm not sure where is the problem is coming from... Will take a look when i have time (which unfortunately is not before sth like mid September...)

**Comment by berkus** [comment]
Thanks!

I'll try to look into how zed works with dev extensions and maybe instrument the process a bit in the mean time.

**Comment by lvillalobos-cr** [comment]
> > Make sure you have rust installed, mine is working after swapping my distro prepackaged rust with rust installed from rutsup
> 
> Yeah, I have rust installed from rustup all the time, I wonder what else may I be missing? I have both stable and nightly, a bunch of toolchains installed too, so whatever it misses it does not say.

I was able to get it to work on the M2 Macbook air by uninstalling the rust package from homebrew and installing **rustup**. I am now able to see zed in my wakatime dashboard!

**Comment by berkus** [comment]
@vectorcr I have only rustup, but that doesn't work.
What configuration do you have in rustup now (which toolchains installed, which targets etc).

**Comment by lvillalobos-cr** [comment]
@berkus It didn’t require me to install any toolchains or targets. This is the order that I followed.

1. Cloned the repo
2. Removed rust from homebrew
3. Installed rustup 
4. Opened Zed
5. Selected dev extension 
6. Selected the cloned folder
7. WakaTime appeared in my plugins list
8. Validated that the editor was appearing in my WakaTime dashboard 

I am still very new to these things so I don’t know what to provide you that would help, but I am willing to provide you with more information if you give me guidance on what you need to see.

**Comment by berkus** [comment]
<img width="480" alt="image" src="https://github.com/user-attachments/assets/4f59ba4c-3863-4389-b4d2-c078efb0b267">

I've managed to install it through a dev version of zed, but i think the addition of this toolchain file might have helped (i have a bunch of rustup toolchains installed, so locking the extension to match zed's was probably it), i will make a PR so you could test it out.

**Comment by berkus** [comment]
There's also a PR on zed https://github.com/zed-industries/zed/pull/16794 to make it clearer what's going on in extension build.

**Comment by berkus** [comment]
It seems to not help, probably you really need a dev version of zed to install a dev extension?

**Comment by berkus** [comment]
Hey, I see it's officially published now! I guess we can close this then.
